### ISSUE TITLE
FYI regex search not working on Mozilla add-on webpage itself

### ISSUE THREAD

**Issue by peter-lyons-kehl** [mortalis13/Regex-Find#12]
Hi Roman,

Thank you for Regex-Find. Even more for making it new Firefox-compatible.

You may want to mention on the add-on page that it doesn't work with page https://addons.mozilla.org/en-US/firefox/addon/regex-find/ itself. It seems that Mozilla restricts what add-ons can do with its websites (probably from preventing tricking the users).

**Comment by mortalis13** [comment]
Hi. It should work now in the version 1.1.9. I added verification for the frame elements which on that page had undefined objects for some reason.
Thanks.

**Comment by peter-lyons-kehl** [comment]
Thanks Roman.
