### ISSUE TITLE
Find not working in Firefox 50

### ISSUE THREAD

**Issue by NicolasWebDev** [mortalis13/Regex-Find#6]
Hi,

with the current release of FF developer edition (50.0a2) on Archlinux, enabling the Regex-Find plugin makes the "find in page" not working anymore.

When clicking on the toolbar find button, nothing appears, when using ctrl-f neither.

Disabling the addon makes everything work again.

Thanks.

**Comment by chimericdream** [comment]
:+1: on this. I love being able to search with RegEx.

**Comment by DwordPtr** [comment]
It also doesn't work on Ubuntu 16.04.1 with Developer Edition.

**Comment by cuter44** [comment]
Neither on FF Dev 51.0a2 (2016-11-13) (64 bit), Windows 7. RegexFind-1.1.1-signed.

**Comment by DwordPtr** [comment]
Now that firefox 50 is the default in the ubuntu repos this is broken for me and foresee-ably all other's who use firefox on xenial as well.

**Comment by lucaboesch** [comment]
Observing this behaviour with Firefox 50.0 on macOS as well.

**Comment by drelephant** [comment]
Same behaviour on Firefox 50.0.1 on Windows, also previously on 50.0.

I can't use this plugin anymore. Like probably all the people using this plugin, I need to use find in page *all the time*!

**Comment by DwordPtr** [comment]
@drelephant I had to temporarily disable. It's a shame since this plugin is so awesome.

**Comment by cuter44** [comment]
```
_updateEntireWord	chrome://global/content/bindings/findbar.xml:646:11
_updateFindUI		chrome://global/content/bindings/findbar.xml:974:11
open			chrome://global/content/bindings/findbar.xml:728:11
startFind		chrome://global/content/bindings/findbar.xml:1141:11
onFindCommand		chrome://global/content/bindings/findbar.xml:1190:18
toggleFindbar		chrome://regexfind/content/lib.js:331:5
oncommand		chrome://browser/content/browser.xul:1:1
```

This is what observed while I'm debugging the add-on, it yields out while find bar is called.

Content around `findbar:646:11` is:
```xml
641      <method name="_updateEntireWord">
642        <body><![CDATA[
643          let entireWord = this._entireWord;
644          let checkbox = this.getElement("find-entire-word");
645          let statusLabel = this.getElement("entire-word-status");
646          checkbox.checked = entireWord;
...
657        ]]></body>
```

Try eval `gFindBar.getElement("find-entire-word")` and `gFindBar.getElement("entire-word-status")` both return null, but mentioned nodes existed in the head of the same file.  
Eval same statements on FF 46 and also return null. The difference is, seem that FF 46 does not call this method on find bar init (so it doesn't fail, but displaying a toolbar without such "find-entire-word" feature).
![default](https://cloud.githubusercontent.com/assets/2285039/20809300/adcb6464-b840-11e6-8e64-df1c9b9d5fc5.png)

Unfortnately I am not an expert in this scope, manage to search in MDN for hours but failed.   
All that I can help is so much. If someone is skilled on it and know the cure, please leave a note to teach me. Thanks in advance.

**Tip**: Theoretically, by adding a `return` to noop this method you may get it work again...

**Comment by norstbox** [comment]
@cuter44 
As a quick fix you can do the following:
1) Unpack (unzip)`regexfind@findbar.org.xpi` extension.
2) Apply the following patch to the file `content/regexfindbar.xml`:

```diff
--- regexfindbar.xml.orig	2016-04-24 21:26:59.203125000 +0300
+++ regexfindbar.xml	2016-12-03 19:22:52.277656000 +0300
@@ -58,3 +58,11 @@
                xbl:inherits="accesskey=matchcaseaccesskey"/>
-     
+       <xul:toolbarbutton anonid="find-entire-word"
+                         class="findbar-entire-word findbar-button tabbable"
+                         label="&entireWord.label;"
+                         accesskey="&entireWord.accesskey;"
+                         tooltiptext="&entireWord.tooltiptext;"
+                         oncommand="_setEntireWord(this.checked);"
+                         type="checkbox"
+                         xbl:inherits="accesskey=entirewordaccesskey"/>
+			    
       <xul:toolbarbutton anonid="find-regex"
@@ -67,2 +75,3 @@
       <xul:label anonid="match-case-status" class="findbar-find-fast"/>
+      <xul:label anonid="entire-word-status" class="findbar-find-fast"/>
       <xul:label anonid="found-matches" class="findbar-find-fast found-matches" hidden="true"/>
```

3) Change addon ID in `install.rdf` and repack (zip archive with `.xpi` ext) it again.
4) Sign modified `regexfind@findbar.org.xpi` using [Developer Hub signing service](https://addons.mozilla.org/en-US/developers/addon/submit/distribution).

I hope we will get a (proper) fix from the author any time soon.

**Comment by hanaokaiwa** [comment]
I made a pull request for supporting firefox 50.0.
I do not know how to sign the addon packages. Could any body sign the package, please?

**Comment by mortalis13** [comment]
Hi all.
Sorry for not answering. I completely didn't have time for my side projects. Especially for this one requiring deeper investigation.
Thank you all for your attention to this addon.

**hanaokaiwa**, thank you for your contribution. I've checked the code though without completely debugging all the new functions/changes. It works in the **Firefox Developer Edition 52.0a2**.

I'll upload the code to the addon repository. It´ll be signed and available for the the _normal Firefox_ edition. Suppose it will work there too. The new version will be **1.1.2**.

**Comment by DwordPtr** [comment]
@mortalis13 you rule \m/

**Comment by NicolasWebDev** [comment]
Thanks @mortalis13.

**Comment by chimericdream** [comment]
@mortalis13, I was super excited to install the latest version, but when I try to install 1.1.2 from the Moz Addons site, I get a message that the extension is corrupt. I tried downloading the repo and renaming the zip to xpi, but got the same message.

**Comment by hanaokaiwa** [comment]
@chimericdream 
1. The files in the repo are not signed yet, you can only install it on developer edition.
2. The zip file you downloaded from the repo contains a folder named Regex-Find-master, you need to unzip it and zip all files and folders in folder Regex-Find-master again.

**Comment by chimericdream** [comment]
@hanaokaiwa I tried to install it on the developer edition, but had forgotten to allow unsigned addons. I did know to remove the `master` branch folder from the hierarchy in the zip file before renaming it to xpi, but since I hadn't changed the setting in `about:config` it didn't affect it anyway. That said, I updated the setting and installed from Moz Addons successfully. Glad to have regex searching back!

**Comment by mortalis13** [comment]
Hi. The addon is still in the review queue (position 66 of 127) (after 4 days).
Some time before the review process was faster...
So the current version is still 1.1.1.
Please wait until it finishes and the addon has v1.1.2.

I'm glad it's usefull for the people. Thanks.

**Comment by mortalis13** [comment]
The version 1.1.2 is ready.
Please try it.
Good luck.
Hope I find some time later to improve the addon ...

**Comment by davidebaldini** [comment]
Version 1.1.2 becomes incompatible with Firefox 45, as now the search bar is not shown _there_.
Firefox 45 is the current "extended support release" on Debian.

**Comment by DwordPtr** [comment]
Works on xenial!

**Comment by NicolasWebDev** [comment]
Works in FF 51.0a2. Thanks for your help!

**Comment by dklann** [comment]
Works on Ubuntu 16.10 with Firefox 52.0.2. Thanks for this!
